Etoo la
idrice24/mns pull request #428
Opened 2021-01-18 10:07 UTC by idrice24

2021-01-18 15:49 UTC, Ghislain1 requested changes

2021-01-18 15:49 UTC, Ghislain1 commented on package.json
> +    "ngx-moment": "^5.0.0",
Check the function from angular framework first

2021-01-18 15:50 UTC, Ghislain1 commented on package.json
> +    "ngx-moment": "^5.0.0",
Please dont use another library : **ANAGULAR should provide that feature** to format a  time /date

2021-01-18 15:52 UTC, Ghislain1 commented
read this page   we are going to talk about it this weekend

https://angular.io/api/common/DatePipe

2021-01-19 21:00 UTC, idrice24 commented
Ok but what I did, what us bad there or wrong on it??

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎18/‎01/‎2021 16:52
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Author" <author@noreply.github.com>
Objet : Re: [idrice24/mns] Etoo la (#428)

read this page we are going to talk about it this weekend
https://angular.io/api/common/DatePipe
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-19 21:24 UTC, idrice24 commented
https://www.npmjs.com/package/ngx-moment
It is an angular library 

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎18/‎01/‎2021 16:52
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Author" <author@noreply.github.com>
Objet : Re: [idrice24/mns] Etoo la (#428)

read this page we are going to talk about it this weekend
https://angular.io/api/common/DatePipe
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-19 21:24 UTC, idrice24 commented
I checked ngx-moment is the only want that can do what we are expecting !!

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎18/‎01/‎2021 16:49
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Author" <author@noreply.github.com>
Objet : Re: [idrice24/mns] Etoo la (#428)

@Ghislain1 requested changes on this pull request.



In package.json:
> @@ -45,6 +44,9 @@
     "emailjs-com": "^2.6.4",
     "firebase": "^8.1.1",
     "jquery": "^3.5.1",
+    "moment": "^2.29.1",
+    "ngx": "^2.4.0",
+    "ngx-moment": "^5.0.0",
Check the function from angular framework first
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-01-20 13:26 UTC, Ghislain1 commented
Use angular legacy library . NOt externe library

2021-01-20 19:31 UTC, idrice24 commented
And if angular does not have what we want to do, what should I do??

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎20/‎01/‎2021 14:26
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Author" <author@noreply.github.com>
Objet : Re: [idrice24/mns] Etoo la (#428)

Use angular legacy library . NOt externe library
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-02 18:23 UTC, closed without merging