Update README.md
idrice24/mns pull request #435
Opened 2021-01-31 08:18 UTC by gerard5595

Hallo

2021-02-02 18:22 UTC, Ghislain1 commented
@gerard5595  COOL;  you can do pr

2021-02-02 18:22 UTC, Ghislain1 requested changes

2021-02-02 18:22 UTC, Ghislain1 commented on README.md
> +1.  [] Hallo
remove it

2021-02-12 15:17 UTC, closed without merging

2021-02-13 14:43 UTC, gerard5595 commented on README.md
> +1.  [] Hallo
Okya

2021-02-13 14:43 UTC, gerard5595 commented on README.md
> +1.  [] Hallo
Done